### ISSUE TITLE
UI: Settings page header

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#39]
When building options pages, make sure to stick with the core WP UI.  This is the UI that users are familiar with.  Any deviation from that makes the plugin look unprofessional.

There are several issues in the following screenshot.

1. There shouldn't be a "box" around the page title area with the red border.
2. Don't change the style of the page title itself.
3. The save button should be at the bottom of the page.
4. The save button should be a `primary` button, not `secondary`.
5. The save button should be an actual `<button>` rather than a link.

![settings-header](https://cloud.githubusercontent.com/assets/1816309/23591486/b6501908-01b6-11e7-8ef7-649cba479ea6.png)

**Comment by fmdalpiaz** [comment]
Hey @Desertsnowman,
I've only missed the fifth item:

> 5. The save button should be an actual `<button>` rather than a link.

I've take a look on the code and it still an `<a>` element.

**Comment by Desertsnowman** [comment]
Doh! sorry, fixing now

**Comment by krugazul** [comment]
Ive checked the button changes, they all seem to be there.  

@Desertsnowman  I did add in 2 lines of CSS because the spinner wasnt showing nicely (the transparent bg made it look block on the blue button). 
https://github.com/lightspeeddevelopment/tour-operator/commit/d00c0fa517822e82a4f6904a46caba40aed6c7cf#diff-6b2f6833e79a750bf7f3a84223058d3e
