### ISSUE TITLE
PHP 5.6 support?

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#41]
I disabled the fail-safe in the plugin and am testing with PHP 5.2.4 (the lowest WP supports).  It seems to be working thus far.  Admittedly, I'm only in the early stages of testing the plugin.

Is there a reason that you've made the plugin 5.6+ only?

**Comment by eleshar** [comment]
@justintadlock We had a discussion internally on what the minimum supported version will be and reached a consensus that we will be aiming for PHP 5.6+ mainly for two reasons.

1) It was the recommended version for WordPress listed at that stage: https://wordpress.org/about/requirements/ - Notably it has been increased to PHP 7 since then.
2) PHP 5.5 and lower that has already reached its End of Life and is no longer supported by the PHP project.

**Comment by justintadlock** [comment]
Understood.  However, I wouldn't bail out unless your plugin actually has code that requires PHP 5.6.  That's just my personal opinion anyway.  But, this is up to you all.

**Comment by ashleyshaw** [comment]
@justintadlock this minimum version has actually been an issue on a couple of sites. 

@eleshar is there a way for you to scan the code to detect the minimum PHP version required?

**Comment by krugazul** [comment]
@ashleyshaw and @eleshar we have a function which does a compatibility check for PHP, it deactivates the plugin if the version is not PHP 7.0 or higher.  I have updated the notice it outputs to say 7.0 and not 5.6.
